print("Hello World")
print("This is an example\n\n\nTo see it prints")
print("how is it going")
print()
print("yes")
print("And then there he stood saying\"we have an infestation\"")
print('you can also you single quotes to "go around" this confusion')
